akka {
  loglevel = "INFO"
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
  loggers = ["akka.event.slf4j.Slf4jLogger"]

  actor {
    provider = "local"
  }

  http {
    server {
      idle-timeout = 60s
      request-timeout = 60s
    }
  }
}